services:
  archlinux:
    container_name: arch-builder
    image: local/archlinux-custom
    build:
      context: .
    working_dir: /aur
    volumes:
      - ./doom:/aur
    command: sh -c "pacman -Syyu && runuser -ubuilder -- ./doom.sh"
    #command: sh -c "cat /etc/makepkg.conf"
